---
- hosts: web123
  tasks:
    - name: cleaning files
      shell: rm -rf ~/test4

    - name: pull
      shell: git clone -b master https://github.com/Saumil343/test4.git
      
    - name: start apache
      shell: sudo systemctl start httpd

    - name: Cleaning Webserver
      shell: rm -rf /var/www/html/*

    - name: cleaning files
      shell: rm -rf ~/test4

    - name: git pull
      shell: git clone https://github.com/Saumil343/test4.git

    - name: git copy
      shell: cp -r ~/test4 /var/www/html/
      
    - name: service restart
      service:
        name: httpd
        state: restarted

